/*
 * generated by Xtext 2.12.0
 */
package dk.sdu.validation

import dk.sdu.wPage.Input
import org.eclipse.xtext.validation.Check
import dk.sdu.wPage.Type
import dk.sdu.wPage.WPagePackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class WPageValidator extends AbstractWPageValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					WPagePackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkOnlySimpleTypesForInput(Input input) {
		if (!(input.variable.value.value instanceof Type)) {
			error('Input can only be used with simple types', WPagePackage.Literals.INPUT__VARIABLE)
		}	
	}
	
	@Check
	def checkBooleans(dk.sdu.wPage.Boolean bool) {
		if (!('true'.equalsIgnoreCase(bool.value) || 'false'.equalsIgnoreCase(bool.value))) {
			error('Boolean types can only be "True" or "False"', WPagePackage.Literals.BOOLEAN__VALUE)
		}
	}
	
}
